version: '3.3'

services:
    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./dbdata:/var/lib/mysql2

    web:
        restart: always
        build: ./mlflow
        image: mlflow_app
        container_name: mlflow_server
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        environment:
            - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root 's3://mlflow' --host 0.0.0.0

    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "80:80"
            - "8002:8002"
            - "3002:3002"
        networks:
            - frontend
        depends_on:
            - web

    s3:
        image: minio/minio:RELEASE.2021-03-17T02-33-02Z
        volumes:
          - ./data_minio:/data
        networks:
            - frontend
            - backend
        expose:
          - "9002"
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        command: server /data --address ":9002"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9002/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3

    registry:
        restart: always
        image: registry:2
        networks:
            - frontend
            - backend
        expose:
            - "3000"
        environment:
            REGISTRY_STORAGE: s3
            REGISTRY_STORAGE_S3_ACCESSKEY: ${AWS_ACCESS_KEY_ID}
            REGISTRY_STORAGE_S3_SECRETKEY: ${AWS_SECRET_ACCESS_KEY}
            REGISTRY_STORAGE_S3_REGIONENDPOINT: ${MLFLOW_S3_ENDPOINT_URL}
            REGISTRY_STORAGE_S3_BUCKET: docker-registry
            REGISTRY_STORAGE_S3_SECURE: "false"
            REGISTRY_STORAGE_S3_region: ignored-for-minio
            REGISTRY_STORAGE_REDIRECT_DISABLE: "true"

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge


# Useful sources:
#   https://towardsdatascience.com/deploy-mlflow-with-docker-compose-8059f16b6039
#   https://medium.com/noodle-labs-the-future-of-ai/introduction-to-mlflow-for-mlops-part-3-database-tracking-minio-artifact-storage-and-registry-9fef196aaf42
